mysite/mymail/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, LoginView
from django_registration.backends.one_step.views import RegistrationView
from . import views


urlpatterns = [
    path('', views.redir, name='home'),
    path('received/<int:page>', views.search_received, name='search_received'),
    path('send/<int:page>', views.search_send, name='search_send'),
    path('templates/<int:page>', views.search_templates, name='search_templates'),
    path('<uuid:message_url>', views.read_message, name='read_message'),
    path('new', views.create_message, name='create_message'),
    path('delete/<uuid:message_url>', views.delete, name='delete'),
    path('just_delete/<uuid:message_url>', views.just_delete, name='just_delete'),
    path('delete/<uuid:message_url>/Template', views.delete_template, name='delete_template'),
    path('new/<uuid:message_url>', views.create_from_template, name='create_from_template'),
    path(r'registration/',
         RegistrationView.as_view(template_name="mymail/registration.html", success_url="/"),
         name='registration'),
    path(r'logout/', LogoutView.as_view(), name='logout'),
    path(r'login/', LoginView.as_view(template_name="mymail/login.html"), name='login_view'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('mymail.urls')),
]

mysite/mymail/models.py
from django.db import models
from django.contrib.auth.models import User
from uuid import uuid4
from multi_email_field.fields import MultiEmailField


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='sender')
    emails = MultiEmailField(blank=True, null=True)
    url = models.UUIDField(default=uuid4, editable=False)
    title = models.CharField(max_length=200, blank=True)
    text = models.TextField(blank=True, null=True)
    send_date = models.DateTimeField('date to send', blank=True, null=True)
    pub_date = models.DateTimeField('date message created', auto_now_add=True)
    show = models.BooleanField(default=True)
    show_template = models.BooleanField(default=False)

    def __str__(self):
        return str(self.title)

    class Meta:
        verbose_name = 'Message'
        verbose_name_plural = 'Messages'


class Receivers(models.Model):
    user = models.ForeignKey(User, blank=True, default=None, related_name='user', on_delete=models.CASCADE)
    read = models.BooleanField(default=False)
    message = models.ForeignKey(Message, blank=True, default=None, related_name='receivers', on_delete=models.CASCADE)
    show = models.BooleanField(default=True)

    def __str__(self):
        return "{} {}".format(str(self.id), str(self.user))


class Metadata(models.Model):
    title = models.CharField(max_length=255, blank=True)
    file = models.FileField(upload_to=r'uploads/%Y/%m/%d/', blank=True)
    message = models.ForeignKey(Message, on_delete=models.CASCADE, null=True, related_name='meta')

    class Meta:
        verbose_name = 'Metadata'
        verbose_name_plural = 'Metadata'

mysite/mymail/forms.py
from django import forms
from .models import User, Message, Metadata
import django.utils.timezone as timezone
from multi_email_field.forms import MultiEmailField
from django.utils.translation import gettext as _


class DateTimeInput(forms.DateTimeInput):
    input_type = "datetime-local"

    def __init__(self, **kwargs):
        kwargs["format"] = "%Y-%m-%dT%H:%M"
        super().__init__(**kwargs)


class MessageForm(forms.ModelForm):
    receivers = forms.ModelMultipleChoiceField(User.objects, required=False,)
    title = forms.CharField(required=False)
    text = forms.Textarea()
    send_date = forms.DateTimeField(required=False, widget=DateTimeInput,
                                    input_formats=["%Y-%m-%dT%H:%M", "%Y-%m-%d %H:%M"])
    emails = MultiEmailField(required=False)
    # file_field = forms.FileField(required=False, widget=forms.ClearableFileInput(attrs={'multiple': True}))

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
        self.fields["emails"].widget.attrs['rows'] = "2"
        self.fields["text"].widget.attrs['rows'] = "2"

    class Meta:
        model = Message
        fields = ['receivers', 'emails', 'title', 'text', 'send_date']

    def clean_send_date(self):
        date = self.cleaned_data.get('send_date')
        cd = self.cleaned_data
        if date:
            if date < timezone.now():
                raise forms.ValidationError(_('Invalid datetime: %(value)s'),
                        params={'value': date},
                    )
        return date

    def clean(self):
        receivers = self.cleaned_data.get('receivers')
        emails = self.cleaned_data.get('emails')
        if not receivers and not emails:
            raise forms.ValidationError(_('Error: No receivers or emails'))
        return self.cleaned_data

mysite/mymail/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, get_object_or_404
from .forms import MessageForm
from .models import Message, Receivers
import datetime
from apscheduler.schedulers.background import BackgroundScheduler
from django.utils.timezone import activate, now
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail
scheduler = BackgroundScheduler()
scheduler.start()


def just_send_mail(message):
    send_mail(message.title, message.text, message.sender, message.emails, fail_silently=False)


def send_mail_sheduled(message):
    if message.send_date:
        scheduler.pause()
        scheduler.add_job(func=just_send_mail, trigger='date',
                          run_date=message.send_date, args=[message], id=str(message.url))
        scheduler.resume()
    else:
        just_send_mail(message)


def del_shcedule(message):
    try:
        scheduler.remove_job(str(message.url))
    except:  # JobLookupError
        print('not found')


def search(request, page, messages, what_search):
    number_print = 30
    more = len(messages) > number_print * (page + 1)
    return render(request, 'mymail/search.html',
                  {"messages": messages[number_print * page: number_print * (page + 1)],
                   "page": page,
                   "more": more, "what_search": what_search})


def search_received(request, page):
    activate('Europe/Kiev')
    if request.user.is_authenticated:
        current_user = request.user
        messages = Receivers.objects.filter(show=True, user=current_user)\
            .exclude(message__send_date__isnull=False,
                     message__send_date__gt=datetime.datetime.now())\
            .order_by('-message')
        return search(request, page, messages, what_search='Received messages')
    else:
        return render(request, 'mymail/search.html', {'what_search': 'Received messages'})


def search_send(request, page):
    activate('Europe/Kiev')
    if request.user.is_authenticated:
        current_user = request.user
        messages = Message.objects.filter(sender=current_user, show=True).order_by('-id')
        return search(request, page, messages, what_search='Send messages')
    else:
        return render(request, 'mymail/search.html', {'what_search': 'Send messages'})


def read_message(request, message_url):
    activate('Europe/Kiev')
    current_user = request.user
    try:
        message = Message.objects.get(url=str(message_url))
        receiver = message.receivers.filter(user=current_user)
        if current_user == message.sender:
            if message.send_date and message.send_date > now():
                initial_dict = {
                    "title": message.title,
                    "receivers": [r.user for r in message.receivers.all()],
                    "text": message.text,
                    "send_date": message.send_date,
                    "emails": message.emails
                }
                form = MessageForm(request.POST or None, initial=initial_dict)
                if request.method == "POST" and form.is_valid():
                    data = form.cleaned_data
                    message.title = data.get('title')
                    message.text = data.get('text')
                    message.send_date = data.get('send_date')
                    receivers_user = data.get('receivers')

                    to_delete = list(message.receivers.all().exclude(user__in=receivers_user))
                    ids=[r.user.id for r in message.receivers.all()]
                    to_add = list(receivers_user.exclude(id=current_user.id).exclude(id__in=ids))

                    for i in range(min(len(to_delete), len(to_add))):
                        r = to_delete.pop()
                        r.user = to_add.pop()
                        r.save()
                    for r in to_delete:
                        r.delete()
                    for u in to_add:
                        r = Receivers(user=u, message=message)
                        r.save()

                    if message.emails:
                        del_shcedule(message)
                    message.emails = data.get('emails')
                    if current_user in receivers_user:
                        message.show_template = True
                    message.save()

                    if message.emails:
                        send_mail_sheduled(message)

                    return redirect('send/0')
                return render(request, 'mymail/edit.html', locals())

        elif receiver:
            if not message.send_date or message.send_date < now():
                receiver = receiver.get()
                receiver.read = True
                receiver.save()
            else:
                message = ''
        else:
            message = ''
    except ObjectDoesNotExist:
        message = 'ObjectDoesNotExist'
        print('__ERROR__')
    return render(
        request,
        'mymail/read_message.html', {"message": message, "current_user": current_user}
    )


def redir(request):
    return redirect('received/0')


def search_templates(request, page):
    activate('Europe/Kiev')
    if request.user.is_authenticated:
        current_user = request.user
        messages = Message.objects.filter(sender=current_user, show_template=True).order_by('-id')
        return search(request, page, messages, 'Templates')
    else:
        return render(request, 'mymail/search.html', {'what_search': 'Templates'})


def delete(request, message_url):
    message = get_object_or_404(Message, url=message_url)
    user = request.user
    if user.is_authenticated:
        if message.sender == user:
            message.show = False
            message.save()
        elif user in [r.user for r in message.receivers.all()]:
            r = message.receivers.get(user=user)
            r.show = False
            r.save()
        delete_mess_without_show(message)
    return redirect('search_received', page=0)


def delete_template(request, message_url):
    message = get_object_or_404(Message, url=message_url)
    user = request.user
    if user.is_authenticated and message.sender == user:
        message.show_template = False
        message.save()
        delete_mess_without_show(message)
    return redirect('search_templates', page=0)


def delete_mess_without_show(message):
    if message.show is False and not message.receivers.filter(show=True) and not message.show_template:
        del_shcedule(message)
        message.delete()


def just_delete(request, message_url):
    message = get_object_or_404(Message, url=message_url)
    if request.user == message.sender and message.send_date > now():
        del_shcedule(message)
        message.delete()
    return redirect('home')


def creation(request, form, template=False, message=''):
    if request.method == "POST" and form.is_valid():
        print("request - {}".format(request.POST))
        data = form.cleaned_data
        print('data', data)
        receivers = data.get('receivers')
        title = data.get('title')
        text = data.get('text')
        send_date = data.get('send_date')
        emails = data.get('emails')

        message = Message(sender=request.user, title=title, text=text, send_date=send_date, emails=emails)
        if request.user in receivers:
            message.show_template = True

            if len(receivers) == 1:
                message.show = False
        message.save()
        if emails:
            send_mail_sheduled(message)
        for receiver in receivers.exclude(id=request.user.id):
            r = Receivers(user=receiver, message=message)
            r.save()
        return redirect('send/0')

    return render(request, "mymail/create_message.html", locals())


def create_from_template(request, message_url):
    activate('Europe/Kiev')
    try:
        message = Message.objects.get(url=message_url, sender=request.user)
        initial_dict = {
            "title": message.title,
            "receivers": [r.user for r in message.receivers.all().exclude(user=request.user)],
            "text": message.text,
            "send_date": message.send_date,
            "emails": message.emails
        }
    except ObjectDoesNotExist:
        return redirect('create_message')
    form = MessageForm(request.POST or None, initial=initial_dict)
    return creation(request, form, True, message)


def create_message(request):
    form = MessageForm(request.POST or None)
    return creation(request, form)

mysite/mymail/templates/mymail/_header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="{% url 'home' %}">Company Mail</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'search_send' 0 %}">Send messages</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'search_received' 0 %}">Received messages</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link disabled" href="{% url 'create_message' %}">Create message</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link disabled" href="{% url 'search_templates' 0 %}">Templates</a>
      </li>
    </ul>
    <div class="col-2">
        {% if user.is_authenticated %}
            <div class="row font-weight-bold text-white h5 mr-2 text-truncate">
                {{ user.username }}
            </div>
            <div class="row">
                <a class="font-weight-bold text-decoration-none text-white h5"
                   href="{% url 'logout' %}">
                    Logout
                </a>
            </div>
        {% else %}
            <div class="row">
                <a class="font-weight-bold text-decoration-none text-white text-justify h5"
                   href="{% url 'login_view' %}">
                    Login
                </a>
            </div>
            <div class="row">
                <a class="font-weight-bold text-decoration-none text-white text-justify h5"
                   href="{% url 'registration' %}">
                    Registration
                </a>
            </div>
        {% endif %}
  </div>
</nav>

mysite/mymail/templates/mymail/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Company Mail</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>

<div class="container-fluid">
    {% include '_header.html' %}
</div>

{% block content %}
{% endblock %}


</body>
</html>

mysite/mymail/templates/mymail/create_message.html
{% include "mymail/base.html" %}

{% block content %}
<div class="container mt-2 ml-2">

{% if user.is_authenticated %}
    <form method="post" action="{% url 'create_message' %}"> {% csrf_token %}
        <div class="form-group">
            <label class="h5 label" for="id_receivers">{{form.receivers.label}}</label>
            {{form.receivers}}
        </div>

        <div class="form-group ">
            <label class="h5 label" for="id_emails">{{form.emails.label}}</label>
            {{ form.emails }}
        </div>

        <div class="form-group row">
            <label class="h5 col-sm-3 col-form-label" for="id_title">{{form.title.label}}:</label>
            <div class="col-sm-9">
                {{ form.title }}
            </div>
        </div>

        <div class="form-group row">
            <label class="h5 col-sm-3 col-form-label" for="id_text">{{form.text.label}}:</label>
            <div class="col-sm-9">
                {{ form.text }}
            </div>
        </div>

        <div class="form-group row">
            <label class="h5 col-3 col-form-label" for="id_send_date">{{form.send_date.label}}:</label>
            <div class="col-9">
                {{form.send_date}}
            </div>
        </div>

        <button class="btn btn-primary" type="submit">Submit form</button>
        {%if form.errors%}
        <div class="alert alert-danger" role="alert">
            {{form.errors}}
        </div>
        {%endif%}
        {% if template %}
        <form action="{% url 'delete' message.url %}" method="post">
            {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="Delete">
        {% endif %}

        <input type="hidden" name="next" value="{{ next }}"/>

    </form>

{% else %}
    <h1 class="ml-5 center text-center">You are not authenticated</h1>
{% endif %}

</div>
{% endblock %}

mysite/mymail/templates/mymail/edit.html
{% include "mymail/base.html" %}
{% block content %}
<div class="container ml-4 mt-2 col-6">

{% if user.is_authenticated %}
    <form action="{% url 'read_message' message.url %}" method="post"> {% csrf_token %}
        <div class="form-group">
            <label class="h5 label" for="id_receivers">{{form.receivers.label}}</label>
            {{form.receivers}}
        </div>

        <div class="form-group">
            <label class="h5 label" for="id_emails">{{form.emails.label}}</label>
            {{ form.emails }}
        </div>

        <div class="form-group row">
            <label class="h5 col-sm-3 col-form-label" for="id_title">{{form.title.label}}:</label>
            <div class="col-sm-9">
                {{ form.title }}
            </div>

        </div>

        <div class="form-group row">
            <label class="h5 col-sm-3 col-form-label" for="id_text">{{form.text.label}}:</label>
            <div class="col-sm-9">
                {{ form.text }}
            </div>

        </div>

        <div class="form-group row">
            <label class="h5 col-3 col-form-label" for="id_send_date">{{form.send_date.label}}:</label>
            <div class="col-9">
                {{form.send_date}}
            </div>
        </div>

        <button class="btn btn-primary" type="submit">Submit form</button>
        <input name="next" type="hidden" value="{{ next }}"/>
        {%if form.errors%}
            <div class="alert alert-danger" role="alert">
                {{form.errors}}
            </div>
        {%endif%}
    </form>

    <form class="mt-1" action="{% url 'just_delete' message.url %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>


{% else %}
    <p>you are not authenticated</p>
    <a href="/login">Login</a>
{% endif %}

</div>
{% endblock %}

mysite/mymail/templates/mymail/login.html
{% include "mymail/base.html" %}
{% block content %}

<div class="container ml-2 mt-2 col-5">

{%if form.errors%}
    <div class="alert alert-danger" role="alert">
        {{form.errors}}
    </div>
{%endif%}

{% if user.is_authenticated %}
    <h1 class="ml-5 center text-center">You are already authenticated</h1>
{% else %}

<form method="post" action="{% url 'login_view' %}"> {% csrf_token %}
    <div class="form-group">
        <label for="Username">Username</label>
        <input name="username" class="form-control" id="Username"   placeholder="Enter username">
    </div>

    <div class="form-group">
        <label for="Password">Password</label>
        <input name="password" type="password" class="form-control" id="Password" placeholder="Password">
        <small id="passwordHelp" class="form-text text-muted">We'll never share your password with anyone else.</small>
    </div>

    <button type="submit" class="btn btn-primary">Login</button>
</form>

{% endif %}
</div>
{% endblock %}

mysite/mymail/templates/mymail/read_message.html
{% include "mymail/base.html" %}

{% block content %}

<div class="container ml-2 mt-2">

{% if message %}
        <p class="h4"> Message detail info</p>
        <hr>
        <p><strong>Sender: </strong>{{ message.sender }}</p>
        <p class="h8">
            {% if message.send_date %}
                {{ message.send_date }}
            {% else %}
                {{ message.pub_date }}
            {% endif %}
        </p>
        <br>

        <p class="h4"><strong>Receivers:</strong></p>
        <div class="ml-5">
            {% for receiver in message.receivers.all %}
                <p class="h6">{{ receiver.user.username }}</p>
            {% endfor %}
            {% for email in message.emails %}
                <p class="h6">{{ email }}</p>
            {% endfor %}
            <p class="h6">{{message.external_receivers}}</p>
        </div>
        <br>

        <p class="h3">{{ message.title }}</p>
        <br>
        <p class="h5 ml-5">{{ message.text }}</p>
        <br>

        <form action="{% url 'delete' message.url %}" method="post">
            {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="Delete">

    </form>
{% endif %}

</div>
{% endblock %}

mysite/mymail/templates/mymail/registration.html
{% include "mymail/base.html" %}
{% block content %}

<div class="container ml-2 mt-2 col-5">

{%if form.errors%}
    <div class="alert alert-danger" role="alert">
        {{form.errors}}
    </div>
{%endif%}

{% if user.is_authenticated %}
    <h1 class="ml-5 center text-center">You are already authenticated</h1>
{% else %}

<form method="post" action=""> {% csrf_token %}
    <div class="form-group">
        <label for="Username">Username</label>
        <input name="username" class="form-control" id="Username"   placeholder="Enter username">
        <small id="loginHelp" class="form-text text-muted">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only</small>

    </div>

    <div class="form-group">
        <label for="Email">Email address</label>
        <input name="email" type="email" class="form-control" id="Email" aria-describedby="emailHelp" placeholder="Enter email">
    </div>

    <div class="form-group">
        <label for="Password">Password</label>
        <input name="password1" type="password" class="form-control" id="Password" placeholder="Password">
        <small id="passwordHelp" class="form-text text-muted">We'll never share your password with anyone else.</small>
        <small id="passwordHelp2" class="form-text text-muted">Your password can’t be too similar to your other personal information.</small>
        <small id="passwordHelp3" class="form-text text-muted">Your password must contain at least 8 characters.</small>
        <small id="passwordHelp4" class="form-text text-muted">Your password can’t be a commonly used password.</small>
        <small id="passwordHelp5" class="form-text text-muted">Your password can’t be entirely numeric..</small>
    </div>

    <div class="form-group">
        <label for="Password2">Password confirmation:</label>
        <input name="password2" type="password" class="form-control" id="Password2" placeholder="Password">
    </div>

    <button type="submit" class="btn btn-primary">Register</button>
    <input type="hidden" name="next" value="{{ next }}" />
</form>

{% endif %}
</div>
{% endblock %}

mysite/mymail/templates/mymail/search.html
{% include "mymail/base.html" %}

{% block content %}

<div class="container ml-2">
{% load mymail_extras %}

{% if user.is_authenticated %}
    <p class="h2 mt-2">{{what_search}}</p>
    {% if messages %}
        <ul class="list-group list-group-flush">
            {% for message in messages %}
                <li class="list-group-item">
                    {% if what_search == "Templates" %}
                        <a style="display:block" href="{% url 'create_from_template' message.url %}" class="text-decoration-none">
                            <div class="h4 text-primary">
                                <div>
                                    {%if message.title%}
                                        {{ message.title　}}
                                    {%else%}
                                        No title
                                    {%endif%}
                                </div>
                                <div class="h6 text-secondary text-truncate">
                                    {{message.text }}
                                </div>
                            </div>

                        </a>
                    {% elif what_search == "Received messages" %}
                       {% if message.read %}
                            <a style="display:block" href="{% url 'read_message' message.message.url %}">
                                    <div class="h4 text-secondary">
                                        <div>
                                            {%if message.message.title%}
                                                {{ message.message.title　}}
                                            {%else%}
                                                No title
                                            {%endif%}
                                        </div>
                                        <div class="h6 text-secondary text-truncate">
                                            {{message.message.text}}
                                        </div>
                                    </div>
                                </a>
                       {% else %}
                            <a style="display:block" href="{% url 'read_message' message.message.url %}">
                                <div class="h4 text-primary">
                                    <div>
                                        {%if message.message.title%}
                                        {{ message.message.title　}}
                                        {%else%}
                                        No title
                                        {%endif%}
                                    </div>
                                    <div class="h6 text-secondary text-truncate">
                                        {{message.message.text}}
                                    </div>
                                </div>
                            </a>
                       {% endif %}
                    {% else %}
                        {%if not message.send_date or  message.date < now  %}
                            <a style="display:block" href="{% url 'read_message' message.url %}">
                                <div class="h4 text-secondary">
                                    <div>
                                        {%if message.title%}
                                            {{ message.title　}}
                                        {%else%}
                                            No title
                                        {%endif%}
                                    </div>
                                    <div class="h6 text-secondary text-truncate">
                                        {{message.text}}
                                    </div>
                                </div>
                            </a>
                        {% else %}
                            <a style="display:block" href="{% url 'read_message' message.url %}">
                                <div class="h4 text-primary">
                                    <div>
                                        {%if message.title%}
                                            {{ message.title　}}
                                        {%else%}
                                            No title
                                        {%endif%}
                                    </div>
                                    <div class="h6 text-secondary text-truncate">
                                        {{message.text}}
                                    </div>
                                </div>
                            </a>
                        {% endif %}
                    {% endif %}
                </li>
            {% endfor %}
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    {% if  page|subtract:1 > -1%}
                    <li class="page-item"><a class="page-link" href="{{ page|subtract:1}}">{{ page|subtract:1}}</a></li>
                    {% endif %}
                    {% if more%}
                    <li class="page-item"><a class="page-link" href="{{ page|add:1}}">{{ page|add:1}}</a></li>
                    {% endif %}
                </ul>
            </nav>
        </ul>

    {% else %}
        <p>No messages.</p>
    {% endif %}
{% else %}
    <h1 class="ml-5 center text-center">You are not authenticated</h1>
{% endif %}

</div>

{% endblock %}